import { lstat, mkdir, readdir, readFile, unlink, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { parseCartridge, safeFilename } from "../../packages/core/src/cartridge";
import { compilePublicSource } from "./compile";
import { normalizeCover } from "./png";
import { MAX_COVER_BYTES, MAX_DIRECTORY_BYTES, type GenerateOptions, type GeneratedCartridge } from "./types";
import { parsePublishingMetadata, validateDirectoryEntries, validateSlug } from "./validate";

interface ValidatedCartridge {
  metadata: GeneratedCartridge;
  normalizedCover: Uint8Array;
}

async function validateCartridgeDirectory(cartridgesDir: string, slug: string): Promise<ValidatedCartridge> {
  validateSlug(slug);
  const directory = join(cartridgesDir, slug);
  const dirents = await readdir(directory, { withFileTypes: true });
  const errors = validateDirectoryEntries(dirents.map(({ name }) => name));
  for (const entry of dirents) {
    const path = join(directory, entry.name);
    const stats = await lstat(path);
    if (stats.isSymbolicLink()) errors.push(`Symbolic links are not allowed: ${entry.name}`);
    else if (!stats.isFile()) errors.push(`Nested cartridge entries are not allowed: ${entry.name}`);
  }
  for (const required of ["game.tynt", "cartridge.json", "cover.png"]) {
    if (!dirents.some(({ name }) => name === required)) errors.push(`Missing required file: ${required}`);
  }
  if (errors.length > 0) throw new Error(errors.join("\n"));

  const paths = dirents.map(({ name }) => join(directory, name));
  const sizes = await Promise.all(paths.map(async (path) => (await lstat(path)).size));
  const totalBytes = sizes.reduce((sum, size) => sum + size, 0);
  if (totalBytes > MAX_DIRECTORY_BYTES) throw new Error("Cartridge directory exceeds 768 KiB");

  const cartridgeText = await readFile(join(directory, "game.tynt"), "utf8");
  const cartridge = parseCartridge(cartridgeText);
  compilePublicSource(cartridge.source);
  const publishing = parsePublishingMetadata(await readFile(join(directory, "cartridge.json"), "utf8"));
  const cover = new Uint8Array(await readFile(join(directory, "cover.png")));
  if (cover.byteLength > MAX_COVER_BYTES) throw new Error("Cartridge cover exceeds 256 KiB");
  const normalizedCover = normalizeCover(cover);

  return {
    normalizedCover,
    metadata: {
      slug,
      filename: safeFilename(cartridge.title),
      title: cartridge.title,
      author: cartridge.author,
      description: cartridge.description,
      controls: cartridge.controls,
      source: cartridge.source,
      coverUrl: `/generated/cartridges/${slug}.png`,
      cartridge,
      ...publishing,
    },
  };
}

function generatedSource(cartridges: GeneratedCartridge[]): string {
  const values = cartridges.map(({ cartridge: _cartridge, ...value }) => value);
  return `// Generated by bun run cartridges:generate. Do not edit.\n\nexport interface PublicCartridge {\n  slug: string;\n  filename: \`${"${string}"}.tynt\`;\n  title: string;\n  author: string;\n  description: string;\n  controls: string;\n  source: string;\n  coverUrl: string;\n  version: 1;\n  tags: string[];\n  license: string;\n  repository?: string;\n}\n\nexport const PUBLIC_CARTRIDGES = ${JSON.stringify(values, null, 2)} as const satisfies readonly PublicCartridge[];\n`;
}

export async function generatePublicCartridges(options: GenerateOptions): Promise<GeneratedCartridge[]> {
  const dirents = await readdir(options.cartridgesDir, { withFileTypes: true });
  const slugs = dirents.filter((entry) => entry.isDirectory() && !entry.name.startsWith("_")).map(({ name }) => name).sort();
  const validated: ValidatedCartridge[] = [];
  const diagnostics: string[] = [];
  for (const slug of slugs) {
    try {
      validated.push(await validateCartridgeDirectory(options.cartridgesDir, slug));
    } catch (error) {
      diagnostics.push(`${slug}:\n${error instanceof Error ? error.message : String(error)}`);
    }
  }
  const cartridges = validated.map(({ metadata }) => metadata);
  const titleOwners = new Map<string, string>();
  for (const cartridge of cartridges) {
    const key = cartridge.title.trim().toLowerCase();
    const existing = titleOwners.get(key);
    if (existing) diagnostics.push(`${cartridge.slug}:\nDuplicate public title also used by ${existing}`);
    else titleOwners.set(key, cartridge.slug);
  }
  if (diagnostics.length > 0) throw new Error(`Public cartridge validation failed:\n${diagnostics.join("\n")}`);

  if (options.check) return cartridges;

  await mkdir(dirname(options.outputFile), { recursive: true });
  await mkdir(options.coverOutputDir, { recursive: true });
  const expectedCovers = new Set(cartridges.map(({ slug }) => `${slug}.png`));
  const existingCovers = await readdir(options.coverOutputDir, { withFileTypes: true });
  await Promise.all(existingCovers
    .filter((entry) => entry.isFile() && entry.name.endsWith(".png") && !expectedCovers.has(entry.name))
    .map((entry) => unlink(join(options.coverOutputDir, entry.name))));
  await Promise.all(validated.map(({ metadata, normalizedCover }) => writeFile(join(options.coverOutputDir, `${metadata.slug}.png`), normalizedCover)));
  const source = generatedSource(cartridges);
  await writeFile(options.outputFile, source);
  return cartridges;
}

if (import.meta.main) {
  const projectRoot = resolve(import.meta.dirname, "../..");
  const check = process.argv.includes("--check");
  const options: GenerateOptions = {
    cartridgesDir: join(projectRoot, "cartridges"),
    outputFile: join(projectRoot, "apps/web/src/generated/public-cartridges.ts"),
    coverOutputDir: join(projectRoot, "apps/web/public/generated/cartridges"),
    check,
  };
  try {
    const cartridges = await generatePublicCartridges(options);
    console.info(`${check ? "Checked" : "Generated"} ${cartridges.length} public cartridges.`);
  } catch (error) {
    console.error(error instanceof Error ? error.message : String(error));
    process.exitCode = 1;
  }
}
